# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\saleRecord.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1134, 826)
        self.TableWidget = TableWidget(Form)
        self.TableWidget.setGeometry(QtCore.QRect(20, 110, 1091, 701))
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(6)
        self.TableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableWidget.setHorizontalHeaderItem(5, item)
        self.SearchLineEdit = SearchLineEdit(Form)
        self.SearchLineEdit.setGeometry(QtCore.QRect(450, 28, 361, 33))
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.pltComboBox = ComboBox(Form)
        self.pltComboBox.setGeometry(QtCore.QRect(10, 20, 181, 41))
        self.pltComboBox.setObjectName("pltComboBox")
        self.searchItem = ComboBox(Form)
        self.searchItem.setGeometry(QtCore.QRect(260, 20, 181, 41))
        self.searchItem.setObjectName("searchItem")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.TableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "#"))
        item = self.TableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "发货平台"))
        item = self.TableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "发货账号"))
        item = self.TableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "收货账号"))
        item = self.TableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "报价ID"))
        item = self.TableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "确认报价时间"))
from qfluentwidgets import ComboBox, SearchLineEdit, TableWidget
