# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\setting.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1134, 826)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setKerning(True)
        Form.setFont(font)
        self.CardWidget = CardWidget(Form)
        self.CardWidget.setGeometry(QtCore.QRect(10, 10, 551, 331))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setKerning(True)
        self.CardWidget.setFont(font)
        self.CardWidget.setObjectName("CardWidget")
        self.saveProxyConfig = PushButton(self.CardWidget)
        self.saveProxyConfig.setGeometry(QtCore.QRect(150, 260, 121, 61))
        self.saveProxyConfig.setObjectName("saveProxyConfig")
        self.TitleLabel = TitleLabel(self.CardWidget)
        self.TitleLabel.setGeometry(QtCore.QRect(10, 80, 131, 51))
        self.TitleLabel.setObjectName("TitleLabel")
        self.TitleLabel_2 = TitleLabel(self.CardWidget)
        self.TitleLabel_2.setGeometry(QtCore.QRect(10, 170, 131, 51))
        self.TitleLabel_2.setObjectName("TitleLabel_2")
        self.useProxy = CheckBox(self.CardWidget)
        self.useProxy.setGeometry(QtCore.QRect(150, 20, 121, 51))
        self.useProxy.setObjectName("useProxy")
        self.proxyPort = LineEdit(self.CardWidget)
        self.proxyPort.setGeometry(QtCore.QRect(150, 90, 131, 46))
        self.proxyPort.setMinimumSize(QtCore.QSize(0, 46))
        self.proxyPort.setObjectName("proxyPort")
        self.proxyAddress = LineEdit(self.CardWidget)
        self.proxyAddress.setGeometry(QtCore.QRect(150, 180, 181, 46))
        self.proxyAddress.setMinimumSize(QtCore.QSize(0, 46))
        self.proxyAddress.setObjectName("proxyAddress")
        self.TreadCardWidget = CardWidget(Form)
        self.TreadCardWidget.setGeometry(QtCore.QRect(10, 350, 1111, 461))
        self.TreadCardWidget.setObjectName("TreadCardWidget")
        self.BuffAutoSendTradeOffer = CheckBox(self.TreadCardWidget)
        self.BuffAutoSendTradeOffer.setGeometry(QtCore.QRect(20, 20, 171, 41))
        self.BuffAutoSendTradeOffer.setObjectName("BuffAutoSendTradeOffer")
        self.UUAutoSendTradeOffer = CheckBox(self.TreadCardWidget)
        self.UUAutoSendTradeOffer.setGeometry(QtCore.QRect(20, 80, 171, 41))
        self.UUAutoSendTradeOffer.setObjectName("UUAutoSendTradeOffer")
        self.BuffAutoVerifyTradeOffer = CheckBox(self.TreadCardWidget)
        self.BuffAutoVerifyTradeOffer.setGeometry(QtCore.QRect(440, 20, 171, 41))
        self.BuffAutoVerifyTradeOffer.setObjectName("BuffAutoVerifyTradeOffer")
        self.UUAutoVerifyTradeOffer = CheckBox(self.TreadCardWidget)
        self.UUAutoVerifyTradeOffer.setGeometry(QtCore.QRect(440, 80, 171, 41))
        self.UUAutoVerifyTradeOffer.setObjectName("UUAutoVerifyTradeOffer")
        self.CaptionLabel = CaptionLabel(self.TreadCardWidget)
        self.CaptionLabel.setGeometry(QtCore.QRect(440, 120, 281, 131))
        self.CaptionLabel.setObjectName("CaptionLabel")
        self.CaptionLabel_2 = CaptionLabel(self.TreadCardWidget)
        self.CaptionLabel_2.setGeometry(QtCore.QRect(20, 130, 221, 131))
        self.CaptionLabel_2.setObjectName("CaptionLabel_2")
        self.goGIthub = PushButton(Form)
        self.goGIthub.setGeometry(QtCore.QRect(880, 30, 191, 61))
        self.goGIthub.setObjectName("goGIthub")
        self.updateVersion = PushButton(Form)
        self.updateVersion.setGeometry(QtCore.QRect(880, 120, 191, 61))
        self.updateVersion.setObjectName("updateVersion")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveProxyConfig.setText(_translate("Form", "保存代理配置"))
        self.TitleLabel.setText(_translate("Form", "代理端口："))
        self.TitleLabel_2.setText(_translate("Form", "代理地址："))
        self.useProxy.setText(_translate("Form", "使用代理"))
        self.BuffAutoSendTradeOffer.setText(_translate("Form", "BUFF 主动发送报价"))
        self.UUAutoSendTradeOffer.setText(_translate("Form", "UU 主动发送报价"))
        self.BuffAutoVerifyTradeOffer.setText(_translate("Form", "BUFF 自动确认报价"))
        self.UUAutoVerifyTradeOffer.setText(_translate("Form", "UU 自动确认报价"))
        self.CaptionLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">当BUFF或UU Cookie在有效期内，才会去查询BUFF</span></p><p><span style=\" font-weight:600;\">或UU平台上需要确认的报价的订单，当找到订单后，</span></p><p><span style=\" font-weight:600;\">会匹配订单的饰品的AssetId，确认后确定报价！</span></p></body></html>"))
        self.CaptionLabel_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">当BUFF或UU Cookie在有效期内，</span></p><p><span style=\" font-weight:600;\">才会去查询BUFF或UU平台上需要主动</span></p><p><span style=\" font-weight:600;\">发起报价的订单，当找到订单后，会</span></p><p><span style=\" font-weight:600;\">匹配出售的饰品的AssetId进行发货！</span></p></body></html>"))
        self.goGIthub.setText(_translate("Form", "GITHUB"))
        self.updateVersion.setText(_translate("Form", "获取最新版"))
from qfluentwidgets import CaptionLabel, CardWidget, CheckBox, LineEdit, PushButton, TitleLabel
